spring:
  profiles:
    active: ${APP_PROFILE:dev}
  jpa:
    open-in-view: false

security:
  oauth2:
    client:
      client-id: ${CLIENT_ID:dscatalog}
      client-secret: ${CLIENT_SECRET:dscatalog123}

jwt:
  secret: ${JWT_SECRET:MY_JWT_SECRET}
  duration: ${JWT_DURATION:86400}





